services:
  - type: web
    name: raja-rani-royale
    env: node
    plan: free
    region: oregon
    buildCommand: npm run render:build
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
